# Generated by Django 3.1.4 on 2021-11-28 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Article')),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0, verbose_name='Prix')),
                ('image', models.ImageField(upload_to='')),
                ('stock', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible ?')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name="Categorie de l'article")),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_date'],
            },
        ),
    ]
