# Generated by Django 3.2.4 on 2021-12-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('couleur', 'couleur'), ('taille', 'taille')], max_length=100, verbose_name='Caracteristiques'),
        ),
    ]
