# Generated by Django 3.1.4 on 2021-11-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211129_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('Neuf', 'Neuf'), ('Usag', 'Usagé'), ('Ancien', 'Ancien')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, choices=[('GN', 'GUINEE'), ('US', 'USA'), ('FR', 'FRANCE'), ('MA', 'MAROC'), ('CA', 'CANADA'), ('BR', 'BRESIL'), ('AR', 'ARGENTINE'), ('DE', 'ALLEMAGNE'), ('IT', 'ITALIE'), ('ES', 'ESPAGNE'), ('PT', 'PORTUGAL'), ('RU', 'RUSSIE'), ('IN', 'INDE'), ('ID', 'INDONESIE'), ('IN', 'Indiana'), ('MY', 'MALAYSIE'), ('CN', 'CHINE'), ('JP', 'JAPON'), ('UK', 'ANGLETERRE'), ('NL', 'PAYS BAS'), ('BE', 'BELGIQUE')], max_length=50, verbose_name='Fabricant'),
        ),
    ]
