# Generated by Django 3.1.4 on 2021-11-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=80, verbose_name='Categorie')),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.TextField()),
                ('category_image', models.ImageField(upload_to='', verbose_name='Image de la categorie')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
